Form/Type/FontType.php
<?php

declare(strict_types=1);

/*
 * This file is part of the MediaModule for Zikula.
 *
 * (c) Christian Flach <hi@christianflach.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cmfcmf\Module\MediaModule\Form\Type;

use Cmfcmf\Module\MediaModule\Font\FontCollection;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Translation\Extractor\Annotation\Ignore;

/**
 * Displays a font selector.
 */
class FontType extends AbstractType
{
    /**
     * @var FontCollection
     */
    private $fontCollection;

    public function __construct(FontCollection $fontCollection)
    {
        $this->fontCollection = $fontCollection;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'expanded' => true,
            'choices' => /** @Ignore */ $this->fontCollection->getFontsForForm()
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['fontUrl'] = $this->fontCollection->getFontUrl();
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return ChoiceType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'cmfcmfmediamodule_font_choice';
    }
}

Resources/views/CollectionTemplate/Cards.html.twig
{% include 'CmfcmfMediaModule::util.html.twig' %}

{{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:css/vendor/cards.css'), 98) }}

{% import _self as macro %}
{% macro box(title, supportText, buttons, thumbnail, sortableId, icon, mediaTypeTitle) %}
    <div class="col-xs-12 col-sm-6 col-sm-4 col-md-3{% if sortableId %} sortable{% endif %}" style="padding: 10px"{% if sortableId %} data-id="{{ sortableId|e('html_attr') }}"{% endif %}>
        <div class="card">
            {% if sortableId %}
                <i class="fa fa-sort fa-lg" style="position:absolute; cursor: move; top: 10px; right: 10px;"></i>
            {% endif %}
            {% if thumbnail %}
                <img class="card-img-top" src="{{ thumbnail }}" alt="" style="width: 100%;">
            {% endif %}
            <div class="card-block">
                <h4 class="card-title">
                    {% if not thumbnail %}
                        <small>{{ mediaTypeTitle }}</small>
                    {% endif %}
                    {{ title }}
                </h4>
                {% if supportText is not empty %}
                    <p class="card-text">
                        {{ supportText|raw }}
                    </p>
                {% endif %}
                {% for button in buttons %}
                    <a class="card-link" href="{{ button.url }}">
                        {{ button.text }}
                    </a>
                {% endfor %}
            </div>
            <i class="fa fa-fw {{ icon|e('html_attr') }}" style="position: absolute; right: 5px; bottom: 5px;"></i>
        </div>
    </div>
{% endmacro %}

{% set hasParentOrChildCollection = false %}
{% block collections %}
    {% if showChildCollections %}
        <div class="row">
            {% for child in collection.children %}
                {% set hasParentOrChildCollection = true %}
                {% set buttons = [{url: path('cmfcmfmediamodule_collection_display', {slug: child.slug}), text: __('View collection')}] %}
                {% set thumbnail = false %}
                {% set supportText = '' %}
                {% if child.mediaForThumbnail is not null %}
                    {% set thumbnail = mediaTypeCollection.mediaTypeFromEntity(child.mediaForThumbnail).thumbnail(child.mediaForThumbnail, 200, 150, 'url') %}
                    {% if child.mediaForThumbnail.attribution is not empty %}
                        {% set supportText = __('Cover') ~ ' ' ~ child.mediaForThumbnail.attribution %}
                    {% endif %}
                {% endif %}
                {% set supportText = supportText ~ child|cmfcmfmediamodule_getdescription %}
                {{ macro.box(child.title, supportText, buttons, thumbnail, false, 'fa-list', false) }}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% if hasParentOrChildCollection %}
    <h1>{{ __('Media') }}</h1>
{% endif %}

{% block media %}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/Sortable.min.js'), 98) }}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/Collection/sort.js')) }}
    <div class="row" id="cmfcmfmedia-media-sortable-container">
        {% for media in collection.media %}
            {% set supportText = '' %}
            {% if media.attribution is not empty %}
                {% set supportText = media.attribution %}
            {% endif %}
            {% set buttons = [{url: path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug}), text: __('View media')}] %}
            {% if media.downloadAllowed is defined and media.downloadAllowed %}
                {% set buttons = buttons|merge([{url: path('cmfcmfmediamodule_media_download', {slug: media.slug, collectionSlug: media.collection.slug}), text: __('Download')}]) %}
            {% endif %}
            {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
            {{ macro.box(media.title, supportText, buttons, mediaType.thumbnail(media, 200, 150, 'url'), media.id, mediaType.icon, mediaType.displayName) }}
        {% else %}
            {% if not collection.virtualRoot  %}
                <div class="col-xs-12">
                    <div class="alert alert-info">
                        {{ __('This collection is currently empty!') }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

Resources/views/CollectionTemplate/Grid.html.twig
{% extends 'CmfcmfMediaModule:CollectionTemplate:Cards.html.twig' %}

{% block media %}
    {{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:css/Media/Display/grid.css')) }}
    {% set attributions = {} %}
    <div class="cmfcmfmedia-display-grid">
        {% for media in collection.media %}
            {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
            {% set thumbnail = mediaType.thumbnail(media, 300, 200, 'url','inset') %}
            <a href="{{ path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}"{% if not thumbnail %} style="padding-top: 30px; padding-bottom: 20px; border: 1px solid #cecece;-webkit-border-radius: 3px;-moz-border-radius: 3px;border-radius: 3px;"{% endif %}>
                {% if media.attribution is not empty %}
                    {% set attributions = attributions|merge({('m' ~ loop.index): media.attribution}) %}
                    <span class="label label-info cmfcmfmedia-display-grid-attribution-label">{{ loop.index }}</span>
                {% endif %}
                {% if thumbnail %}
                    <img src="{{ thumbnail|e('html_attr') }}" />
                {% else %}
                    <span style="line-height: 20px;">{{ media.title }}</span>
                    <i class="fa fa-fw {{ mediaType.icon|e('html_attr') }}" style="position: absolute; left: 5px; top: 5px;"></i>
                {% endif %}
            </a>
        {% endfor %}
    </div>
    {% if attributions is not empty %}
        <h4>{{ __('Attributions') }}</h4>
        <ul>
            {% for index, attribution in attributions %}
                <li>{{ index|slice(1) }}: {{ attribution|raw }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

Resources/views/CollectionTemplate/Slider.html.twig
{% extends 'CmfcmfMediaModule:CollectionTemplate:Cards.html.twig' %}

{% block media %}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/slick/slick.min.js'), 98) }}
    {{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:js/vendor/slick/slick.css'), 98) }}
    {{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:js/vendor/slick/slick-theme.css'), 99) }}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/Media/Display/slider.js')) }}

    <div id="cmfcmfmedia-display-slider">
        {% for media in collection.media %}
            <div>
                {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
                {% set bigThumbnail = mediaType.thumbnail(media, 800, 450, 'url', 'inset') %}
                <a href="{{ path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}">
                    {% if bigThumbnail %}
                        <img data-lazy="{{ bigThumbnail|e('html_attr') }}" />
                    {% else %}
                        <i class="fa fa-fw fa-5x {{ mediaType.icon }}"></i>
                        {{ media|cmfcmfmediamodule_getdescription }}
                    {% endif %}
                </a>
                {% if media.title is not empty %}
                    <h4>
                        {{ media.title }}
                    </h4>
                {% endif %}
                {% if media.attribution is not empty %}
                    <h5>
                        {{ media.attribution|raw }}
                    </h5>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

Resources/views/CollectionTemplate/cards.html.twig
{% include '@CmfcmfMediaModule/util.html.twig' %}

{{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:css/vendor/cards.css'), 98) }}

{{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/masonry.pkgd.min.js'), 98) }}
{{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/imagesloaded.pkgd.min.js'), 98) }}
{{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/Sortable.min.js'), 98) }}
{{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/Collection/cards.js')) }}

{% import _self as macro %}
{% macro box(title, supportText, buttons, thumbnail, sortableId, icon, mediaTypeTitle) %}
    <div class="col-xs-12 col-sm-6 col-sm-4 col-md-3{% if sortableId %} sortable{% endif %}" style="padding: 10px"{% if sortableId %} data-id="{{ sortableId|e('html_attr') }}"{% endif %}>
        <div class="card">
            {% if sortableId %}
                <i class="fas fa-sort fa-lg d-none" style="position:absolute; cursor: move; top: 10px; right: 10px"></i>
            {% endif %}
            {% if thumbnail %}
                <img class="card-img-top" src="{{ thumbnail }}" alt="" style="width: 100%">
            {% endif %}
            <div class="card-block">
                <h4 class="card-title">
                    {% if not thumbnail %}
                        <small>{{ mediaTypeTitle }}</small>
                    {% endif %}
                    {{ title }}
                </h4>
                {% if supportText|default %}
                    <p class="card-text">
                        {{ supportText|raw }}
                    </p>
                {% endif %}
                {% for button in buttons %}
                    <a class="card-link" href="{{ button.url }}">
                        {{ button.text }}
                    </a>
                {% endfor %}
            </div>
            <i class="fa-fw {{ icon|e('html_attr') }}" style="position: absolute; right: 5px; bottom: 5px;"></i>
        </div>
    </div>
{% endmacro %}


{% set editCollectionPermission = cmfcmfmediamodule_hasPermission(collection, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_EDIT_COLLECTION')) %}
{% set editMediaPermission = cmfcmfmediamodule_hasPermission(collection, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_EDIT_MEDIA')) %}

{% if editMediaPermission or editCollectionPermission %}
    <button class="btn btn-secondary btn-sm" type="button" autocomplete="off" id="cmfcmfmedia-sortable-btn">
        <i class="fas fa-sort"></i> {% trans %}Sort items{% endtrans %}
    </button>
{% endif %}

{% set hasParentOrChildCollection = false %}
{% block collections %}
    {% if showChildCollections %}
        <div class="masonry-grid row" id="cmfcmfmedia-collection-sortable-container">
            {% for child in collection.children %}
                {% if cmfcmfmediamodule_hasPermission(child, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_OVERVIEW')) %}
                    {% set hasParentOrChildCollection = true %}
                    {% set buttons = [{url: path('cmfcmfmediamodule_collection_display', {slug: child.slug}), text: 'View collection'|trans}] %}
                    {% set thumbnail = false %}
                    {% set supportText = '' %}
                    {% if child.mediaForThumbnail|default %}
                        {% set thumbnail = mediaTypeCollection.mediaTypeFromEntity(child.mediaForThumbnail).thumbnail(child.mediaForThumbnail, 200, 150, 'url') %}
                        {% if child.mediaForThumbnail.attribution|default %}
                            {% set supportText = 'Cover'|trans ~ ' ' ~ 'By %s'|trans({'%s': child.mediaForThumbnail.attribution})|lower ~ '<br>' %}
                        {% endif %}
                    {% endif %}
                    {% set supportText = supportText ~ child|cmfcmfmediamodule_getdescription %}
                    {{ macro.box(child.title, supportText, buttons, thumbnail, editCollectionPermission ? child.id : false, 'fas fa-folder', false) }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% if hasParentOrChildCollection %}
    <h1>{% trans %}Media{% endtrans %}</h1>
{% endif %}

{% block media %}
    <div class="masonry-grid row" id="cmfcmfmedia-media-sortable-container">
        {% for media in collection.media %}
            {% set supportText = '' %}
            {% if media.attribution|default %}
                {% set supportText = 'By %s%'|trans({'%s%': media.attribution}) %}
            {% endif %}
            {% set buttons = [{url: path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug}), text: 'View'|trans}] %}
            {% if media.downloadAllowed|default %}
                {% set buttons = buttons|merge([{url: path('cmfcmfmediamodule_media_download', {slug: media.slug, collectionSlug: media.collection.slug}), text: 'Download'|trans}]) %}
            {% endif %}
            {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
            {{ macro.box(media.title, supportText, buttons, mediaType.thumbnail(media, 200, 150, 'url'), editMediaPermission ? media.id : false, mediaType.icon, mediaType.displayName) }}
        {% else %}
            {% if collection.children is empty %}
                <div class="col-xs-12">
                    <div class="alert alert-info">
                        {% trans %}This collection is currently empty!{% endtrans %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

Resources/views/CollectionTemplate/galleria.html.twig
{% extends 'CmfcmfMediaModule:CollectionTemplate:cards.html.twig' %}

{% block media %}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/galleria/galleria.min.js'), 98) }}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/galleria/themes/classic/galleria.classic.min.js'), 99) }}
    {{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:js/vendor/galleria/themes/classic/galleria.classic.css')) }}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/Media/Display/galleria.js')) }}
    <div id="galleria{{ collection.id }}" class="cmfcmfmedia-display-galleria" data-height="{{ options.height|e('html_attr') }}">
        {% for media in collection.media %}
            {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
            {% set bigThumbnail = mediaType.thumbnail(media, 'original', 'original', 'url', 'inset') %}
            {% set smallThumbnail = mediaType.thumbnail(media, 'original', options.height, 'url', 'inset') %}
            <a href="{{ bigThumbnail }}">
                <img src="{{ smallThumbnail }}" data-title="{% if media.title|default %}{{ media.title }}{% endif %}" data-description="{% if media.attribution|default %}{{ __f('By %s', {'%s': media.attribution})|e('html_attr')|raw }}{% endif %}">
            </a>
        {% endfor %}
    </div>
    {% set customStyle %}
        <style>
            #galleria{{ collection.id }} .galleria-stage {
                width: 100%;
                height: {{ options.height|e('html_attr') }}px !important;
            }
        </style>
    {% endset %}
    {{ pageAddAsset('header', customStyle) }}
{% endblock %}

Resources/views/CollectionTemplate/grid.html.twig
{% extends '@CmfcmfMediaModule/CollectionTemplate/cards.html.twig' %}

{% block media %}
    {{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:css/Media/Display/Grid.css')) }}
    {% set attributions = {} %}
    {% set attributionCounter = 0 %}
    <div class="cmfcmfmedia-display-grid">
        {% for media in collection.media %}
            {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
            {% set thumbnail = mediaType.thumbnail(media, 300, 200, 'url','inset') %}
            <a href="{{ path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}"{% if not thumbnail %} style="padding-top: 30px; padding-bottom: 20px; border: 1px solid #cecece;-webkit-border-radius: 3px;-moz-border-radius: 3px;border-radius: 3px;"{% endif %}>
                {% if media.attribution|default %}
                    {% set attributionCounter = attributionCounter + 1 %}
                    {% set attributions = attributions|merge({('m' ~ attributionCounter): media.attribution}) %}
                    <span class="label label-info cmfcmfmedia-display-grid-attribution-label">{{ attributionCounter }}</span>
                {% endif %}
                {% if thumbnail %}
                    <img src="{{ thumbnail|e('html_attr') }}" />
                {% else %}
                    <span style="line-height: 20px">{{ media.title }}</span>
                    <i class="fa-fw {{ mediaType.icon|e('html_attr') }}" style="position: absolute; left: 5px; top: 5px;"></i>
                {% endif %}
            </a>
        {% endfor %}
    </div>
    {% if attributions|default %}
        <h4>{% trans %}Attributions{% endtrans %}</h4>
        <ul>
            {% for index, attribution in attributions %}
                <li>{{ index|slice(1) }}: {{ 'By %s%'|trans({'%s%': attribution})|raw }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

Resources/views/CollectionTemplate/slider.html.twig
{% extends '@CmfcmfMediaModule/CollectionTemplate/cards.html.twig' %}

{% block media %}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/vendor/slick/slick.min.js'), 98) }}
    {{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:js/vendor/slick/slick.css'), 98) }}
    {{ pageAddAsset('stylesheet', zasset('@CmfcmfMediaModule:js/vendor/slick/slick-theme.css'), 99) }}
    {{ pageAddAsset('javascript', zasset('@CmfcmfMediaModule:js/Media/Display/slider.js')) }}
    {% set customStyle %}
    <style>
        .slick-prev:before, .slick-next:before {
            color: black;
        }
        .slick-slide {
            margin-left: 20px;
            margin-right: 20px;
        }
    </style>
    {% endset %}
    {{ pageAddAsset('header', customStyle) }}

    <div class="cmfcmfmedia-display-slider">
        {% for media in collection.media %}
            <div class="img-thumbnail">
                {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
                {% set bigThumbnail = mediaType.thumbnail(media, 800, 450, 'url', 'inset') %}
                <a href="{{ path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}">
                    {% if bigThumbnail %}
                        <img data-lazy="{{ bigThumbnail|e('html_attr') }}" />
                    {% else %}
                        <i class="fa-fw fa-5x {{ mediaType.icon|e('html_attr') }}"></i>
                        {{ media|cmfcmfmediamodule_getdescription }}
                    {% endif %}
                </a>
                {% if media.title|default %}
                    <h4>{{ media.title }}</h4>
                {% endif %}
                {% if media.attribution|default %}
                    <h5>{{ 'By %s%'|trans({'%s%': media.attribution})|raw }}</h5>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

Resources/views/CollectionTemplate/table.html.twig
{% include '@CmfcmfMediaModule/util.html.twig' %}

<div class="table-responsive">
    <table class="table table-hover">
        <colgroup>
            <col id="cTitle" />
            <col id="cLicense" />
            <col id="cAuthor" />
            <col id="cActions" />
        </colgroup>
        <thead>
            <tr>
                <th id="hTitle" scope="col">{% trans %}Title{% endtrans %}</th>
                <th id="hLicense" scope="col">{% trans %}License{% endtrans %}</th>
                <th id="hAuthor" scope="col">{% trans %}Author{% endtrans %}</th>
                <th id="hActions" scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% if showChildCollections %}
            {% if collection.parent is not null %}
                {% set parentCollectionPermission = cmfcmfmediamodule_hasPermission(collection.parent, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_OVERVIEW')) %}
                {% if parentCollectionPermission %}
                    <tr class="active">
                        <td headers="hTitle">
                            <a href="{{ path('cmfcmfmediamodule_collection_display', {slug: collection.parent.slug})|e('html_attr') }}">
                                <i class="fas fa-fw fa-folder"></i> ..
                            </a>
                        </td>
                        <td colspan="3"></td>
                    </tr>
                {% endif %}
            {% endif %}
            {% set editCollectionPermission = cmfcmfmediamodule_hasPermission(collection, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_EDIT_COLLECTION')) %}
            {% for child in collection.children %}
                {% if cmfcmfmediamodule_hasPermission(child, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_OVERVIEW')) %}
                    <tr>
                        <th headers="hTitle" scope="row" colspan="3">
                            <a href="{{ path('cmfcmfmediamodule_collection_display', {slug: child.slug})|e('html_attr') }}">
                                <i class="fas fa-fw fa-folder"></i> {{ child.title }}
                            </a>
                        </th>
                        <td headers="hActions" class="text-right">
                            <a class="btn btn-secondary btn-xs" href="{{ path('cmfcmfmediamodule_collection_display', {slug: child.slug})|e('html_attr') }}">
                                <i class="fas fa-search"></i> {% trans %}View collection{% endtrans %}
                            </a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endif %}
        {# Media #}
        {% set viewMediaPermission = cmfcmfmediamodule_hasPermission(collection, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_MEDIA_DETAILS')) %}
        {% set downloadMediaPermission = cmfcmfmediamodule_hasPermission(collection, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_DOWNLOAD_SINGLE_MEDIUM')) %}
        {% set editMediaPermission = cmfcmfmediamodule_hasPermission(collection, constant('Cmfcmf\\Module\\MediaModule\\Security\\CollectionPermission\\CollectionPermissionSecurityTree::PERM_LEVEL_EDIT_MEDIA')) %}
        {% for media in collection.media %}
            <tr>
                <th headers="hTitle" scope="row">
                    {% if viewMediaPermission %}
                        <a href="{{ path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}">
                    {% endif %}
                            {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(media) %}
                            <i class="fa-fw {{ mediaType.icon|e('html_attr') }}"></i>
                        {{ media.title }}
                    {% if viewMediaPermission %}
                        </a>
                    {% endif %}
                </th>
                <td headers="hLicense">
                    {% if media.license is not null %}
                        {% if media.license.url is not null %}
                            <a href="{{ media.license.url|e('html_attr') }}" title="{{ media.license.title }}">
                        {% endif %}
                                {% if media.license.imageUrl is not null %}
                                    <img src="{{ media.license.imageUrl|e('html_attr') }}" />
                                {% else %}
                                    {{ media.license.title }}
                                {% endif %}
                        {% if media.license.url is not null %}
                            </a>
                        {% endif %}
                    {% else %}
                        {% trans %}Unkown{% endtrans %}
                    {% endif %}
                </td>
                <td headers="hAuthor">
                    {% if media.attribution|default %}
                        {{ 'By %s%'|trans({'%s%': media.attribution})|raw }}
                    {% endif %}
                </td>
                <td headers="hActions" class="text-right">
                    {% if viewMediaPermission %}
                        <a class="btn btn-secondary btn-xs" href="{{ path('cmfcmfmediamodule_media_display', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}">
                            <i class="fas fa-search"></i> {% trans %}Details{% endtrans %}
                        </a>
                    {% endif %}
                    {% if downloadMediaPermission and media.downloadAllowed|default %}
                        <a class="btn btn-secondary btn-xs" href="{{ path('cmfcmfmediamodule_media_download', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}">
                            <i class="fas fa-download"></i> {% trans %}Download{% endtrans %}
                        </a>
                    {% endif %}
                    {% if editMediaPermission %}
                        <a class="btn btn-secondary btn-xs" href="{{ path('cmfcmfmediamodule_media_edit', {slug: media.slug, collectionSlug: media.collection.slug})|e('html_attr') }}">
                            <i class="fas fa-pencil-alt"></i> {% trans %}Edit{% endtrans %}
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" class="text-center warning">{% trans %}This collection does not contain media!{% endtrans %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>